import type { ColorPreset } from '@/types/appearance.types'

export const COLOR_PRESETS: ColorPreset[] = [
  {
    id: 'minimalist',
    name: 'Minimalista',
    category: 'minimalist',
    colors: {
      header: { background: '#FFFFFF', text: '#111827', accent: '#000000' },
      navbar: { background: '#FFFFFF', links: '#4B5563', activeLink: '#000000' },
      body: {
        background: '#FFFFFF',
        titles: '#111827',
        text: '#4B5563',
        links: '#111827',
        buttonBg: '#111827',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#111827', titles: '#FFFFFF', text: '#9CA3AF', links: '#D1D5DB' },
    },
  },
  {
    id: 'modern-ocean',
    name: 'Océano Moderno',
    category: 'bold',
    colors: {
      header: { background: '#FFFFFF', text: '#0F172A', accent: '#0EA5E9' },
      navbar: { background: '#0F172A', links: '#BAE6FD', activeLink: '#FFFFFF' },
      body: {
        background: '#F0F9FF',
        titles: '#0F172A',
        text: '#334155',
        links: '#0284C7',
        buttonBg: '#0EA5E9',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#0F172A', titles: '#E0F2FE', text: '#94A3B8', links: '#38BDF8' },
    },
  },
  {
    id: 'vibrant-sunset',
    name: 'Atardecer Vibrante',
    category: 'bold',
    colors: {
      header: { background: '#FFFBEB', text: '#78350F', accent: '#F97316' },
      navbar: { background: '#F97316', links: '#FFF7ED', activeLink: '#FFFFFF' },
      body: {
        background: '#FFFBEB',
        titles: '#78350F',
        text: '#92400E',
        links: '#EA580C',
        buttonBg: '#F97316',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#7C2D12', titles: '#FED7AA', text: '#FDBA74', links: '#FB923C' },
    },
  },
  {
    id: 'classic-professional',
    name: 'Profesional Clásico',
    category: 'minimalist',
    colors: {
      header: { background: '#FFFFFF', text: '#1E293B', accent: '#475569' },
      navbar: { background: '#1E293B', links: '#CBD5E1', activeLink: '#FFFFFF' },
      body: {
        background: '#F8FAFC',
        titles: '#0F172A',
        text: '#475569',
        links: '#1E40AF',
        buttonBg: '#1E293B',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#0F172A', titles: '#E2E8F0', text: '#94A3B8', links: '#CBD5E1' },
    },
  },
  {
    id: 'eco-friendly',
    name: 'Eco-Friendly',
    category: 'bold',
    colors: {
      header: { background: '#F0FDF4', text: '#14532D', accent: '#16A34A' },
      navbar: { background: '#166534', links: '#BBF7D0', activeLink: '#FFFFFF' },
      body: {
        background: '#F0FDF4',
        titles: '#14532D',
        text: '#365314',
        links: '#16A34A',
        buttonBg: '#16A34A',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#14532D', titles: '#BBF7D0', text: '#86EFAC', links: '#4ADE80' },
    },
  },
  {
    id: 'midnight-indigo',
    name: 'Medianoche',
    category: 'dark',
    colors: {
      header: { background: '#1E1B4B', text: '#C7D2FE', accent: '#818CF8' },
      navbar: { background: '#312E81', links: '#A5B4FC', activeLink: '#FFFFFF' },
      body: {
        background: '#0F0E2A',
        titles: '#E0E7FF',
        text: '#A5B4FC',
        links: '#818CF8',
        buttonBg: '#6366F1',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#0C0A24', titles: '#C7D2FE', text: '#6366F1', links: '#818CF8' },
    },
  },
  {
    id: 'earth-tones',
    name: 'Tonos Tierra',
    category: 'luxury',
    colors: {
      header: { background: '#FFFBEB', text: '#78350F', accent: '#B45309' },
      navbar: { background: '#78350F', links: '#FDE68A', activeLink: '#FFFFFF' },
      body: {
        background: '#FAF7F2',
        titles: '#451A03',
        text: '#78350F',
        links: '#B45309',
        buttonBg: '#92400E',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#292524', titles: '#FDE68A', text: '#A8A29E', links: '#D6D3D1' },
    },
  },
  {
    id: 'soft-pastel',
    name: 'Pastel Suave',
    category: 'pastel',
    colors: {
      header: { background: '#FDF2F8', text: '#831843', accent: '#EC4899' },
      navbar: { background: '#FFFFFF', links: '#9D174D', activeLink: '#BE185D' },
      body: {
        background: '#FFF1F2',
        titles: '#881337',
        text: '#9F1239',
        links: '#DB2777',
        buttonBg: '#EC4899',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#831843', titles: '#FBCFE8', text: '#F9A8D4', links: '#F472B6' },
    },
  },
  {
    id: 'high-contrast',
    name: 'Alto Contraste',
    category: 'bold',
    colors: {
      header: { background: '#000000', text: '#FFFFFF', accent: '#FBBF24' },
      navbar: { background: '#FBBF24', links: '#000000', activeLink: '#1F2937' },
      body: {
        background: '#FFFFFF',
        titles: '#000000',
        text: '#1F2937',
        links: '#B45309',
        buttonBg: '#000000',
        buttonText: '#FBBF24',
      },
      footer: { background: '#000000', titles: '#FBBF24', text: '#D1D5DB', links: '#FBBF24' },
    },
  },
  {
    id: 'luxury-gold',
    name: 'Lujo Dorado',
    category: 'luxury',
    colors: {
      header: { background: '#1C1917', text: '#D4AF37', accent: '#D4AF37' },
      navbar: { background: '#292524', links: '#D6D3D1', activeLink: '#D4AF37' },
      body: {
        background: '#FAFAF9',
        titles: '#1C1917',
        text: '#44403C',
        links: '#B45309',
        buttonBg: '#1C1917',
        buttonText: '#D4AF37',
      },
      footer: { background: '#1C1917', titles: '#D4AF37', text: '#A8A29E', links: '#D4AF37' },
    },
  },
  {
    id: 'lavender-dream',
    name: 'Lavanda',
    category: 'pastel',
    colors: {
      header: { background: '#FAF5FF', text: '#581C87', accent: '#A855F7' },
      navbar: { background: '#FFFFFF', links: '#7E22CE', activeLink: '#9333EA' },
      body: {
        background: '#FAF5FF',
        titles: '#3B0764',
        text: '#6B21A8',
        links: '#9333EA',
        buttonBg: '#A855F7',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#3B0764', titles: '#E9D5FF', text: '#C084FC', links: '#D8B4FE' },
    },
  },
  {
    id: 'dark-emerald',
    name: 'Esmeralda Oscura',
    category: 'dark',
    colors: {
      header: { background: '#022C22', text: '#A7F3D0', accent: '#34D399' },
      navbar: { background: '#064E3B', links: '#6EE7B7', activeLink: '#FFFFFF' },
      body: {
        background: '#0D1F17',
        titles: '#A7F3D0',
        text: '#6EE7B7',
        links: '#34D399',
        buttonBg: '#059669',
        buttonText: '#FFFFFF',
      },
      footer: { background: '#022C22', titles: '#6EE7B7', text: '#34D399', links: '#A7F3D0' },
    },
  },
]
